### ISSUE TITLE
Figure out a way to retain python2 compatibility while modularizing `cqlsh`

### ISSUE THREAD

**Issue by jeffwidman** [jeffwidman/cqlsh#13]
The changes in #7 are great, but break under py2: #11 

I like the changes in #7 and don't want to revert them, so see if there's a straightforward way to tweak it to make it compatible with py2.

**Comment by bschoening** [comment]
FYI, Cassandra 4.1 scheduled for April 2022 release will remove python 2.7 compatibility.

**Comment by jeffwidman** [comment]
Sounds like an easy way to deal with this. 

We'll just need to be sure the `Classifiers` and `python_requires` sections are updated appropriately before cutting that release.

(and also pull in the `4.1` version of the `cqlsh` code)

**Comment by jeffwidman** [comment]
I'm going to close this... even though it's not present here, `cassandra` `trunk` already removed Python 2, which will arrive with `cassandra` `4.1`. I opened a draft PR so once it's ready/merged, this will be a non-issue. In the meantime, our `master` branch here is still broken under Python 2, and that's just fine since the actual release on PyPI is still python 2 compatible.
