### ISSUE TITLE
strip_comment_blocks logic is reversed.

### ISSUE THREAD

**Issue by wshang2022** [jeffwidman/cqlsh#17]
I believe the logic is reversed. The strip_comment_blocks is meant to remove comments in "..." so it should not go into the _if_ section if re.search('["].*[/][*].*[*][/].*["]', statementtext) return None.
https://github.com/jeffwidman/cqlsh/blob/master/cqlsh/cqlsh.py#L905

example:
INSERT INTO DB (abc) VALUES ('/*');

**Comment by jeffwidman** [comment]
It looks like this bug is with `cqlsh` itself... this repo is just the packaging to put it on PyPI.

So can you file a Jira against upstream Cassandra project?

More info here: https://github.com/jeffwidman/cqlsh#contributing

**Comment by bschoening** [comment]
Jeff is correct, that you'll need to file a bug against the upstream Apache Cassandra project.  
When I tried this, with a comment in the CQL command, it worked fine.

DESCRIBE /* foo */ keyspaces;
