### ISSUE TITLE
Consolidate `setup.py`, `setup.cfg`, `pyproject.toml` into `pyproject.toml`

### ISSUE THREAD

**Issue by jeffwidman** [jeffwidman/cqlsh#38]
@bschoening reminded me that this project still uses `setup.py` and `setup.cfg`... modern python packaging seems to be standardizing on `pyproject.toml`, so should migrate fully to that at some point...

**Comment by bschoening** [comment]
@jeffwidman with the 6.2.0 release, the distro could almost be built from the Apache repo.  All it needs is to add 
a)  __main__.py to Apache Cassandra's cqlshlib and 
b) the build file(s) setup.py, setup.cfg, and pyprojct.toml. 

Thus, if we can simplify and consolidate those build files, it would make incorporating them to Apache Cassandra easier. 

I've created a draft branch with this change at https://github.com/jeffwidman/cqlsh/blob/pyproject-toml/pyproject.toml

**Comment by bschoening** [comment]
Resolved
