### ISSUE TITLE
Support for Python 3.12

### ISSUE THREAD

**Issue by Bx1** [jeffwidman/cqlsh#41]
Now Ubuntu 24.04 LTS comes with updated version of Python 3.12. Currently `cqlsh` (Cassandra 5.0) doesn't work with this version of python.

> Warning: unsupported version of Python, required 3.6-3.11 but found 3.12
> No appropriate Python interpreter found.

**Comment by bschoening** [comment]
@Bx1 The CQLSH 5.0 distribution on PyPi which will support Python 3.12 has been released now.
