### ISSUE TITLE
Python module for CQLSH

### ISSUE THREAD

**Issue by bschoening** [jeffwidman/cqlsh#5]
First, this package can't be executed using the Python facility for executing modules as scripts

$ python -m cqlsh
python.exe: No module named cqlsh

Second, cqlsh can't be imported as a module.  Thus, libraries like:

    https://github.com/slowenthal/cql_kernel and 
    https://github.com/bschoening/cqljupyter

copy and paste the cqlsh.py code.  Making this a module would allow for reuse of cqlsh.py and other libraries could simply import 'cqlsh'.

**Comment by jeffwidman** [comment]
Completely agree. I'd happily merge a PR making the change so it can be both used as a script and importable.

**Comment by jeffwidman** [comment]
Closed by #7 - thanks @bschoening for the fix.
