### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jeffwidman** [jeffwidman/cqlsh#8]
The changes in #7 merit a new release.

For simplicity, probably be nice to get a fix for #4 first so that we don't have to cut two releases one right after the other.

cc @bschoening

**Comment by jeffwidman** [comment]
And we're live: https://pypi.org/project/cqlsh/6.0.1/

🍾 

@bschoening let me know if you hit any unexpected issues.

**Comment by bschoening** [comment]
Nice!  thanks much!!
